### ISSUE TITLE
Expo stuck, and unable to run via QR scan or web

### ISSUE THREAD

**Issue by fardiansyah1808** [obytes/react-native-template-obytes#349]
# Summary:
When running `pnpm start` to start Expo, I am unable to run the app via the Expo QR scan. Additionally, when running via the web, it gets stuck while doing expo-router/entry.js.

## Steps to reproduce:
1. Run `pnpm start` in the project.
2. Attempt to scan the QR code with Expo Go.
3. Alternatively, try running the app via the web.

## Environment::
1. Expo SDK: 51.0.31
2. expo-router: ~3.5.23
3. Node:  v20.17.0
4. npm: 10.8.2
5. Operating System: Windows 11 Pro Build 22621

## Expected behavior:
The application should start normally and be accessible via the Expo QR scan or the web without getting stuck.

## Additional notes:
The issue seems to be related to `expo-router`. The problem is not entirely similar to the one described [here](https://stackoverflow.com/questions/78494804/expo-stuck-on-welcome-to-expo-screen), but it might be related.

## Attachment
![image](https://github.com/user-attachments/assets/4f51e59a-1927-4ff2-a825-9bc191d88c13)

**Comment by hmurovich** [comment]
Hi @yjose, I have the same issue with web build, could you please clarify whether your starter supports web build or not?

**Comment by eessadrati** [comment]
any updates? i have the same issue

**Comment by hmurovich** [comment]
Hi @yjose @eessadrati @fardiansyah1808. I figured it out, it was nativewind windows path issue: https://github.com/nativewind/nativewind/issues/610
As temp fix in src\app\_layout.tsx change "import '../../global.css';" to "import '../../node_modules/.cache/nativewind/global.css.web.css';" (it will work only for web build)

**Comment by eessadrati** [comment]
`pnpm install nativewind@4.0.25`
fixed my issue

**Comment by yjose** [comment]
@hmurovich yeah apparently we are still facing some issues with NativeWind on Windows devices. We are just waiting for the new official release of NativeWind to fix this issue.

Please try the suggestion from @eessadrati to fix the issue.

**Comment by yjose** [comment]
should be fixed as we migrate to the last nativewind version
